### ISSUE TITLE
Add snippet variants with 'class' instead of 'className'

### ISSUE THREAD

**Issue by Lockhild** [emranweb/daisyui-snippet#17]
Hi! First of all, thank you for the effort you've put into this extension! It's great.
Second, is there an easy way for you to also add a way to choose `class` instead of `className`? SolidJS, for example, uses `class`.

<img width="1129" alt="image" src="https://github.com/emranweb/daisyui-snippet/assets/41568834/a7c44785-370a-479d-b517-9a129c8e8383">

**Comment by emranweb** [comment]
@Lockhild, thanks for your feedback,
I will check SolidJS and update it soon.

**Comment by emranweb** [comment]
I have added a setting that allows you to switch between class and className.
[daisyui-snippet-0.0.7.vsix.zip](https://github.com/emranweb/daisyui-snippet/files/13980991/daisyui-snippet-0.0.7.vsix.zip)

Please test this extension build from your side and update me.

Here is the step you can use the package.

- Uninstall my current extension
- Download the zip file and extract 
- Open vscode and go to the extension section, open settings, and click install from VSIX
- Select my vsix package that you extract 
- After installation, click daisyUI snippets and go to extension settings.
- Check Mark the setting and Reload the vscode

**Must - Reload the vscode after changing the setting** 

## Images 
![image](https://github.com/emranweb/daisyui-snippet/assets/5980298/72fe5691-03de-4367-b742-04b5f5acceb2)
![image](https://github.com/emranweb/daisyui-snippet/assets/5980298/b3670af0-7099-4385-9ff2-879031f09b90)
![image](https://github.com/emranweb/daisyui-snippet/assets/5980298/3c436d18-4fee-4839-a4df-3624924f6fcd)
