### ISSUE TITLE
[Feature Request] Add autocomplete support for .astro

### ISSUE THREAD

**Issue by sltrip** [emranweb/daisyui-snippet#18]
Astro is another framework known for its Islands architecture. The file extension is `.astro`, and the template code is written similar to HTML.

![image](https://github.com/emranweb/daisyui-snippet/assets/141436069/e6174b16-db1c-4a53-898c-e8bfe9c7a597)

**Comment by liyunhe17** [comment]
This is my try: https://github.com/emranweb/daisyui-snippet/pull/19

**Comment by emranweb** [comment]
@liyunhe17  Thanks for your work. I will check and
