### ISSUE TITLE
Use Class not functioning

### ISSUE THREAD

**Issue by NexRX** [emranweb/daisyui-snippet#33]
Hi, thank you for the extension! Super useful!

Im using solidjs and for some reason the Use Class toggle has no effect. I have restarted a few times but not luck. Anything i can provide to help you debug this?

I have followed your steps here: https://github.com/emranweb/daisyui-snippet/discussions/23

**Comment by emranweb** [comment]
@NexRX thanks for your feedback. I am checking

**Comment by emranweb** [comment]
@NexRX I have checked the issue but It was fine on my device, can you please share more information about the problem?

**Comment by NexRX** [comment]
@emranweb I'm not really sure what more I can share but im on Windows using vscode 1.91.1 using Node 20. 
I've tried
```json
{
    "daisyui.useClass": true
}
```

In both workspace and user settings.json to no success. Every time i still get `className` instead of `class`.

I was going to try and create a series of reproducible steps using https://vscode.dev but looks like this extension isn't available via browser. Is that something hard to support? :)

**Comment by emranweb** [comment]
I checked both Mac and Windows but did not find the issue. Please let me know if you are still having the problem. Thanks
